<html>
<head>
    <title>Episode Search</title>

    <!-- style sheets -->
    <?= $this->headLink()->appendStylesheet('http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'); ?>
    <?= $this->headLink()->appendStylesheet('http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css'); ?>
    <?= $this->headLink()->appendStylesheet('css/EpisodeSearch.css'); ?>

    <!-- javascript -->
    <?= $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js', 'text/javascript'); ?>
    <?= $this->headScript()->prependFile('http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js', 'text/javascript'); ?>
    <?= $this->headScript()->prependFile('js/require.js', 'text/javascript'); ?>

</head>
<body>
<div class="container">
    <h2>Episode Search</h2>

    <!--Episode search widget that can be included into any page-->
    <?php echo $this->partial('index/searchWidget.phtml'); ?>

    <!--Footer-->
    <hr>
    <footer>
        <p>Martin Buckley - 2014</p>
    </footer>

</div>
</body>
</html>