<html>
<head>
    <title>Programme Finder</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/ProgrammeFinder.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="js/search.js"></script>
</head>
<body>
<div class="container">
    <h2>Programme Finder</h2>

    <!-- pass this to the javascript -->
    <?php echo $this->url(array('controller' => 'index', 'action' => 'search', 'limit' => 10, 'query' => '')) ?>

    <!-- extract to partial -->
    <div class="episode-search">

        <form name="episode-search-form">
            <input type="text" class="episode-search-field" maxlength="50">

            <div class="episode-search-button"><span class="glyphicon glyphicon-search"></span></div>
        </form>

        <div class="episode-search-results">
            <ul></ul>
        </div>
    </div>

    <!--Footer-->
    <hr>
    <footer>
        <p>Martin Buckley - 2014</p>
    </footer>

</div>
</body>
</html>