<!-- Widget specific JS-->
<script type="text/javascript">
    define('params', {
        searchUrl: "<?= $this->url(array('limit' => 5, 'query' => ''), 'search') ?>"
    });
    require(["js/search"], function (search) {});
</script>

<div class="episode-search">

        <div class="episode-search-form">
            <input type="text" class="episode-search-field" id="searchBox" maxlength="50" placeholder="Find an episode..."/>

            <button class="episode-search-button" id="search"><span class="glyphicon glyphicon-search"></span></button>
        </div>

        <div class="episode-search-results">
            <ul></ul>
        </div>

</div>