<?php foreach ($this->episodes as $episode) : ?>
    <li>
        <div>
            <a href="http://<?= $episode->getLink() ?>">
                <?php if ($episode->hasImage()) : ?>
                    <span>
                    <?=
                    $this->formImage(
                        '',
                        '',
                        array(
                            'src' => $episode->getImage('96x54'),
                            'alt' => $episode->getTitle() . ' image',
                        )
                    );
                    ?>
                    </span>
                <?php endif ?>
                <span><?= $episode->getTitle() ?></span>
            </a>
        </div>
    </li>
<?php endforeach ?>