<?php if(empty($this->episodes)) : ?>
    <li>no results</li>
<?php else :
    foreach ($this->episodes as $episode) : ?>
        <li>
            <a href="http://<?= $this->escape($episode->getLink()) ?>">
                <span>
                    <?=
                    $this->formImage(
                        '',
                        '',
                        array(
                            'src' => $this->imageChef($episode->getImage(), 96, 54),
                            'alt' => $episode->getTitle() . ' image',
                        )
                    );
                    ?>
                </span>
                <span><?= $this->escape($episode->getTitle()) ?></span>
            </a>
        </li>
    <?php endforeach;
endif ?>